local King = loadstring(game:HttpGet("https://raw.githubusercontent.com/Akbar025zzz/KingAkbarUi/main/KingAkbarUI.lua"))()
local UI   = King({ Theme = "Royal" })

local Win = UI:CreateWindow({ Title = "KingAkbarUI Demo", Size = Vector2.new(640, 460) })

local T1 = Win:Tab({ Name = "Overview", Icon = "◆" })
T1:Paragraph({ Title = "Selamat datang", Text = "Library premium dengan 4 tema dan API clean." })
T1:Button({ Name = "Solid",    Style = "Solid",    Callback = function() UI:Notify({ Title = "Sukses", Content = "Solid ditekan", Type = "success" }) end })
T1:Button({ Name = "Gradient", Style = "Gradient", Callback = function() UI:Notify({ Title = "Gradient", Content = "Gradient ditekan", Type = "info" }) end })
T1:Button({ Name = "Outline",  Style = "Outline",  Callback = function() UI:Notify({ Title = "Outline", Content = "Outline ditekan", Type = "warning" }) end })
T1:Toggle({ Name = "Fitur Utama", Default = true, Callback = function(v) print("toggle:", v) end })
T1:Checkbox({ Name = "Saya setuju", Default = false })

local T2 = Win:Tab({ Name = "Input", Icon = "✎" })
T2:Textbox({ Placeholder = "Nama...", Callback = function(t) print("[Textbox]", t) end })
T2:Slider({ Name = "Volume", Min = 0, Max = 100, Default = 45, Suffix = "%", Callback = function(v) print("[Slider]", v) end })
T2:Dropdown({ Name = "Senjata", Options = { "Sword", "Bow", "Staff" }, Search = true, Callback = function(v) print("[Dropdown]", v) end })
T2:Dropdown({ Name = "Warna", Options = { "Merah", "Hijau", "Biru" }, Multi = true, Callback = function(t) print("[Multi]", table.concat(t, ",")) end })
T2:ColorPicker({ Default = Color3.fromRGB(220, 180, 90), Callback = function(c) print("[Color]", c) end })

local T3 = Win:Tab({ Name = "Advanced", Icon = "⚙" })
T3:Label({ Text = "Pilih difficulty:" })
T3:Radio({ Name = "Easy",   Group = "diff", Default = true })
T3:Radio({ Name = "Normal", Group = "diff" })
T3:Radio({ Name = "Hard",   Group = "diff" })
local pb = T3:ProgressBar({ Name = "Loading", Default = 0, Max = 100 })
T3:Button({ Name = "Simulate Load", Callback = function()
    task.spawn(function()
        for i = 0, 100, 5 do pb:Set(i); task.wait(0.05) end
        UI:Notify({ Title = "Selesai", Content = "Loading complete!", Type = "success" })
    end)
end })
local lbl = T3:Label({ Text = "Hover aku untuk tooltip!" })
UI:AttachTooltip(lbl._inst, "Tooltip dari KingAkbarUI ✨")
T3:Button({ Name = "Test Notif", Callback = function()
    UI:Notify({ Title = "Info",    Content = "Info",    Type = "info" })
    task.wait(0.15)
    UI:Notify({ Title = "Success", Content = "Sukses",  Type = "success" })
    task.wait(0.15)
    UI:Notify({ Title = "Warning", Content = "Warning", Type = "warning" })
    task.wait(0.15)
    UI:Notify({ Title = "Error",   Content = "Error",   Type = "error" })
end })
T3:Button({ Name = "Ganti Tema", Callback = function()
    UI.Theme:ToggleMode()
    UI:Notify({ Title = "Tema", Content = "Mode: " .. UI.Theme.Mode, Type = "info" })
end })

print("[KingAkbarUI] Demo ready.")
